[build]
  command = "npm run netlify-build"
  publish = ".output/public"
  functions = ".output/server"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@node-rs/helper"]

[build.environment]
  NODE_VERSION = "20" 