backend:
  name: git-gateway
  branch: main # Branch where commits are pushed

media_folder: "static/images" # Folder for uploaded images
public_folder: "/images" # Folder for accessing images

collections:
  - name: "about"
    label: "About"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "skills"
    label: "Skills"
    folder: "content/skills"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
